### ISSUE TITLE
Input field for filters is missing in the UI

### ISSUE THREAD

**Issue by crazyscientist** [SUSE/aimaas#175]
# Description

When expanding the advanced filtering section, one can select the field and operator.

But if one does that, the input field for the filter value vanishes.

![grafik](https://github.com/SUSE/aimaas/assets/1128117/2ef4a46e-c2b1-4369-8f14-7882cafcf862)

![grafik](https://github.com/SUSE/aimaas/assets/1128117/59c80dfe-0d00-49bb-8ab6-3d005ac315c4)

# Expected behavior

Input field does not vanish.

**Comment by der-gabe** [comment]
So it became a textarea and that's why it disappeared? Amazing... but, like, in a bad way.

Anyway, LGTM!

**Comment by crazyscientist** [comment]
> So it became a textarea and that's why it disappeared?

Yes, and because I forgot to import the `TextareaInput` component. So it rendered as `<textareainput>` :roll_eyes:
