### ISSUE TITLE
cannot reorder package catalog by "use_case"

### ISSUE THREAD

**Issue by dirkmueller** [SUSE/aimaas#180]
in https://aimaas.suse.de/schema/package-catalog it is possible to order / sort the results via name, info, lifecycle, product, reason, support_status. however not for use_case

**Comment by crazyscientist** [comment]
1. Ordering/Sorting by "infos" and "product" ist just as impossible as ordering/sorting by "use_case".
2. "infos" is a multi-valued attribute, where sorting makes no sense.
3. The other attributes ("product" and "use_case") are of type "reference" (i.e. foreign key to a different schema). The API response only contains the IDs of referenced entities. The UI fetches the names in separate API calls.
4. Given the chosen EAV data model on the DB level, sorting a paginated list of entities by the value of referenced entities will be time intensive in terms of development and runtime.
