### ISSUE TITLE
no way to unassign a use case once selected

### ISSUE THREAD

**Issue by dirkmueller** [SUSE/aimaas#183]
what is the UI method for unselecting / unassigning a use case once it got assigned already?

**Comment by crazyscientist** [comment]
Unfortunately, this is "just" a UI issue:

* If an attribute of type reference has a value, the UI shows a delete button on the right:

  ![grafik](https://github.com/SUSE/aimaas/assets/1128117/a3a1bb48-5d77-47e9-805e-c91a8fc00644)
* When one clicks on the button, it shows no effect in the UI.
* However, if one clicks on "save changes", the nullification of the attribute is sent to the server correctly.
