### ISSUE TITLE
Schema attribute changes not reflected in Entity detail page

### ISSUE THREAD

**Issue by TeodoraPavlova** [SUSE/aimaas#203]
If you change the schema attributes and after that go to entity detail page, you won't see schema changes reflected. The changes are visible after page reload.

I thought that we can update the `activeSchema` value with triggering an update in `SchemaEdit` component (if we provide a function, which will do the update in `<App/>`, inject it into `<SchemaEdit/>` and invoke it). It turned out that the `activeSchema` object gets updated, but provide() does not get called again after updating the object. 

It could be possible that at this point this can not be resolved properly (without javascript page reload) and it could be issue related with the usage of the options API. In theory, it should be reactive and the provide() should get called after.

If there is no other easy solution at this point, a page reload (on successful response) will do the job.

**Comment by crazyscientist** [comment]
Nice catch :+1: 

The description currently covers only the client that applied the change to the schema. Maybe we should also consider the impact on other clients that unaware of the schema change?

**Comment by TeodoraPavlova** [comment]
I agree.. it can get very messy, especially if the slug is changed :laughing:

**Comment by TeodoraPavlova** [comment]
> Maybe we should also consider the impact on other clients that unaware of the schema change?

What do you think about implementing server side events for this one? Or just client polling?
