### ISSUE TITLE
Report all Java Package changes to affected teams

### ISSUE THREAD

**Issue by mcalmer** [SUSE/aimaas#5]
Happend in SLE15 SP2 / SUSE Manager 4.1:

- New java packages got released in Development-Tools
- SUSE Manager Team was not informed. They use the same packages but have older versions in there own buildservice projects.
- The new packages moved the "jar" files into a different directory, which break SUSE Manager (dead links for tomcat and taskomatic)
- As "Development Tools" is optional channel and rarely used, it was not found by QA. 

As SUSE Manager is the only product (currently) which use java report all new java packages or incompatible changes to packages to the SUSE Manager Team.

**Comment by rfrohl** [comment]
Isn't there the ECO process to address issues exactly like these ?

**Comment by msmeissn** [comment]
can you specify exactly what happened? also this is the wrong forum, I would suggest mail maint-coord@suse.de

**Comment by msmeissn** [comment]
only java related t4hing i see is SUSE:Maintenance:15514   "ant"

**Comment by mcalmer** [comment]
A lot of java packages were added new to development tools module with SLE15 SP2.
This module is available for SUSE Manager Server, but it is optional.
SUSE Manager had older version (build with tetra which is not allowed in SLE) in its own repo.

The new packages had the same name, but store the JAR files at a different place.

Now the following happened:

Customers migration from 4.0 to 4.1 and have the development tools module enabled, migrated to the package versions in the development module. Our Java app was creating links to the place of our packages and got now broken links. SUSE Manager was not starting.

Nobody was aware of the new added packages. Especially as we had them already.

**Comment by msmeissn** [comment]
The content of the Service Pack at GA level MUST be brought up with sle-release-coord.

**Comment by crazyscientist** [comment]
After careful consideration I would consider this use case to be out of scope of this project. On the other hand your problem sounds more like a use case for the "maintenance checkers" project.

@rfrohl @deneb-alpha Would you like to request something for the "checkers" project?
