### ISSUE TITLE
Set a speaking window title

### ISSUE THREAD

**Issue by tgoettlicher** [SUSE/aimaas#75]
Currently the window title says "frontend". A more speaking window title would be "SUSE Product Lifecycle Database".

**Comment by r-richardson** [comment]
I couldnt find a window titled "frontend", neither locally nor in production. It shows "AIMAAS", no matter what page.
I'd say "AIMAAS" is a good default title, but maybe we should still change it to "SUSE Product Lifecycle Database" for production ?

**Comment by crazyscientist** [comment]
Ah, right. A while back I replaced "frontend" with "AIMAAS" (see 29ad8fb0134b3aa101213052eb73cbdb0f461156)

I would not change the hard-coded package name. What we could consider is to adjust the page title (in the browser) depending on the currently active view :thinking:
