### ISSUE TITLE
Allow bulk change of dates

### ISSUE THREAD

**Issue by celan** [SUSE/aimaas#90]
Sometimes a set of modules or products have a change of lifecycle dates. Without a bulk change that can be tedious.

Use case:
Chris User needs to set a Beta product as released by removing the word "beta" from all affected products and wants to set the actual FCS date, which is not known before it happens.

**Comment by crazyscientist** [comment]
@celan, would it be acceptable, if the dialog for bulk editing would look something like this?

![grafik](https://user-images.githubusercontent.com/1128117/219066383-2b8c7f48-254c-4f23-9e15-b6210769b618.png)

I.e., just repeat the input dialog for all the entities in the selected set?

**Comment by celan** [comment]
Yes, looks good. Thanks!
